version: '2'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/analytics
    container_name: flask-analytics-app
    depends_on:
    - db
  db:
    image: "mongo"
    container_name: flask-analytics-db